### PR TITLE
Cosmetics & temporary ranks

### PR DESCRIPTION
**Pull request by RinesThaix**
- New dependency: lombok
- Rines' lib-classes to work with inventories*, itemstacks & chat
- Actually, some cosmetics stuff

I know there is your in-built lib to work with inventories, but woutos told me there's nothing against adding another one (mine) in order to make it more convenient for me to code cosmetics-related guis.
Also, currently I don't have any test environment, so there's a chance that this update hurts, but whether I'm not retarted and didn't forget something, it doesn't.

### CODE REVIEW

**Comment by Jobarion** [comment]
I reall think this pr should not get accepted without justification. What features are you missing in the current item menu api? And if you want to use a different one, remove the old one. I don't want two libs for the same thing at once.

**Comment by RinesThaix** [comment]
These apis just work in different ways, ie use different styles. I have been developing guis with my api for like 6 months and it's really convenient for me to use it, don't think there are any other reasons for it to be implemented. As I already said, Wouto told me there's nothing against adding another api for working with guis, but since such a situation, I'll remove my inventory lib and recode everything I did using the old one.

**Comment by RinesThaix** [comment]
I've just found a way of testing this stuff and found some bugs. Fixing them.

**Comment by RinesThaix** [comment]
Ok. Now it's stable and probably working the way it should. To sum up, there are:
- New dependency: lombok
- Fix to AutoBroadcaster (there was not notices collection initialization, so there was a NPE)
- Some changes in inventory menu api: method .displayItem(ItemStack) has been returned and is compatible with another methods (such as .displayName(String), .displayIcon(Material) and etc). Also, there's a ClickType field in InventoryMenuClickEvent which allows to determine whether click was left, right, shifted, etc.
- There was already coins system, but I also added premium credits to SLPlayer.
- There's a Collectibles class which contains info about all cosmetic items player owns and about all cosmetic items currently active on the player. All cosmetic items extend class CItem and have their unique id. Also, every CItem is related to one of CTypes: it's enum, which is used to handle conflict issue between different types of CItems. For example, it will be used to disallow players from wearing Emoji to their head whilst there's a helmet active. Currently there's only one CType: Armor. There are also only 3 CItems: Leather, Gold & Diamond armors. Cosmetics submenu is currently marked as 'Work in progress' and is visible/available only to Dev and higher ranks.
- Probably something else. Will update this comment as soon as I remember more.

**Comment by JoshKeighley20** [comment]
@JoBa97 Can we have your updated opinion please?

**Comment by JoshKeighley20** [comment]
Also @RinesThaix would prefer not to use lombok at this time - we haven't used it as of yet and it seems a bit pointless to start now.

**Comment by RinesThaix** [comment]
Removed lombok dependency, implemented /settemprank command. Last push also changes rank changing/loading system a bit and I'm unable to test it on local server so there can be issues (by the way I'm still using your db and don't have connection to socket server).

**Comment by Jobarion** [comment]
Why is that method in SLPlayer called setEternalRank? What is eternal about it?

**Comment by RinesThaix** [comment]
@JoBa97, it has been implemented to resolve the following issue:
Imagine that I bought eternal $$ rank. Then I bought 3 months $$$ rank, so after these 3 months I should get my $$ rank back (instead of default one). The eternal rank field stores info about the rank that will be given to the player after his not-eternal rank expires.

**Comment by Jobarion** [comment]
@RinesThaix That makes sense, yes. The name "eternal" rank is still a bit misleading in my opinion.

**Pull request merged**
